# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.TextField()),
                ('pct_hisp', models.IntegerField(null=True)),
                ('pct_blk', models.IntegerField(null=True)),
                ('pct_white', models.IntegerField(null=True)),
                ('pct_frn_born', models.IntegerField(null=True)),
                ('pct_poverty', models.IntegerField(null=True)),
            ],
        ),
    ]
