# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 21:07
from __future__ import unicode_literals
from django.db import migrations
import json, requests
from census.models import Zip

### START CONFIG ###
url =  'http://api.census.gov/data/2015/acs5/?get=NAME,B23025_002E&for=zip+code+tabulation+area:*&key='
### END CONFIG ###

s = requests.Session()

zip_codes = [z.zip_code for z in Zip.objects.all()]

def make_data_dict():
    """
    {zip:count}
    only for zips in db
    """
    data = s.get(url).json()
    return dict((x[-1],x[1]) for x in data if x[-1] in zip_codes)

def update_workforce_cnts(apps,schema_editor):
    data_dict = make_data_dict()
    for zip_code in data_dict:
        try:
            z = Zip.objects.get(zip_code = zip_code)
        except:
            continue
        z.cnt_workforce = data_dict[zip_code] 
        z.save()


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_zip_cnt_workforce'),
    ]

    operations = [
            migrations.RunPython(update_workforce_cnts)
    ]
