# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.TextField()),
                ('case_type', models.TextField()),
                ('date_filed', models.DateField(null=True)),
                ('date_closed', models.DateField(null=True)),
                ('status', models.TextField()),
                ('claimant_zip_code', models.TextField(null=True)),
                ('employer_zip', models.TextField(null=True)),
                ('employer_name', models.TextField()),
                ('industry', models.TextField()),
                ('amt_claimed', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.TextField()),
                ('date', models.DateField(null=True)),
                ('alj', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MWOT',
            fields=[
                ('complaint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='complaints.Complaint')),
                ('amt_resolved', models.FloatField(null=True)),
                ('claim_type', models.TextField()),
            ],
            bases=('complaints.complaint',),
        ),
        migrations.CreateModel(
            name='WC',
            fields=[
                ('complaint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='complaints.Complaint')),
                ('union_local', models.TextField()),
                ('union_name', models.TextField()),
                ('translation', models.TextField()),
                ('wages', models.FloatField(null=True)),
                ('bonus', models.FloatField(null=True)),
                ('commission', models.FloatField(null=True)),
                ('deductions', models.FloatField(null=True)),
                ('vacation', models.FloatField(null=True)),
            ],
            bases=('complaints.complaint',),
        ),
        migrations.AddField(
            model_name='hearing',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.Complaint'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='claimant_zip_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='census.Zip'),
        ),
    ]
